FROM docker.io/library/mediawiki:<%= mw_version %>

RUN apt-get update && apt-get install -y wget sudo mariadb-client netcat vim

# Convert the built-in www-data user to something that matches the external
# user running the container
RUN find / -xdev -user www-data \! -type l -print0 | xargs -0 chown <%= mw_userid %>
RUN find / -xdev -group www-data \! -type l -print0 | xargs -0 chgrp <%= mw_groupid %>

# And same for the un-named user 1000 that seems to own a bunch of stuff
RUN find / -xdev -user 1000 -print0 | xargs -0 chown <%= mw_userid %>
RUN find / -xdev -group 1000 -print0 | xargs -0 chgrp <%= mw_groupid %>

# Not sure if this'll work?, because our local userid is created by the podman --user argument
RUN usermod -u <%= mw_userid %> www-data
RUN groupmod -g <%= mw_groupid %> www-data

# Prep directorios for cross mounting
RUN rm -rf /var/www/mediawiki/images /var/www/mediawiki/files
RUN mkdir -p /var/www/mediawiki/images /var/www/mediawiki/files
RUN chown -R <%= mw_userid %>:<%= mw_groupid %> /var/www/mediawiki/images /var/www/mediawiki/files

# RUN chown -R <%= mw_userid %>:<%= mw_groupid %> /var/run /var/lib/nginx /usr/local/etc /run /dev/stderr /dev/stdin  /dev/stdout /data /images
RUN echo 'www-data    ALL=(ALL)   NOPASSWD: ALL' >>/etc/sudoers
RUN cat /etc/sudoers

RUN rm -rf /var/www/html/images
RUN ln -s /var/www/mediawiki/images /var/www/html/images
RUN ln -s /var/www/mediawiki/LocalSettings.php /var/www/html/LocalSettings.php
RUN ln -s /var/www/mediawiki/files /var/www/html/files

# Install Extensions
WORKDIR /var/www/html/
COPY grab_extdist.sh /usr/local/bin/
RUN /usr/local/bin/grab_extdist.sh Variables <%= mw_version %>
RUN /usr/local/bin/grab_extdist.sh RSS <%= mw_version %>
RUN /usr/local/bin/grab_extdist.sh ConfirmAccount <%= mw_version %>
RUN /usr/local/bin/grab_extdist.sh SocialProfile <%= mw_version %>
RUN /usr/local/bin/grab_extdist.sh UniversalLanguageSelector <%= mw_version %>

# Set up Apache configs
RUN sed -i 's/Listen 80/Listen 8080/' /etc/apache2/ports.conf
RUN ln -s /etc/apache2/mods-available/remoteip.load /etc/apache2/mods-enabled/remoteip.load
COPY httpd.conf /etc/apache2/sites-available/000-default.conf
