FROM mariadb:<%= db_version %>

ENV MYSQL_ROOT_PASSWORD=<%= File.read('DO_NOT_CHECK_IN/mysql_password.txt').chomp %>

# Convert the built-in uid/gid (999) to something that matches the external
# user running the container
ARG DB_USERID
ARG DB_GROUPID

RUN find / -xdev -user mysql -print0 | xargs -0 chown <%= db_userid %>
RUN find / -xdev -group mysql -print0 | xargs -0 chgrp <%= db_groupid %>
RUN usermod -u <%= db_userid %> mysql
RUN groupmod -g <%= db_groupid %> mysql

RUN sed -i 's/^innodb_buffer_pool_size\s*=\s*.*/innodb_buffer_pool_size = 4G/' /etc/mysql/my.cnf
